# .github/dependabot.yml
version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for package.json and lock files in the root directory
    directory: "/"
    # Check for updates once a week (e.g., Sunday)
    schedule:
      interval: "monthly"
      day: "sun"
    # Label all pull requests as "dependencies"
    labels:
      - "dependencies"
    # Group minor/patch updates into a single PR for less noise
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
